# Generated by Django 4.2 on 2023-04-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_room', models.CharField(max_length=250, verbose_name='Название')),
                ('type_room', models.CharField(max_length=250, verbose_name='Тип номера')),
                ('check_in', models.DateField(verbose_name='Заезд')),
                ('check_out', models.DateField(verbose_name='Выезд')),
                ('number_of_visitors', models.IntegerField(verbose_name='Количество посетителей')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-check_in'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
