# Generated by Django 4.2 on 2023-04-25 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_alter_orders_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='title_room',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='type_room',
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
