# Generated by Django 4.2 on 2023-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_rooms_type_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='type_room',
            field=models.CharField(blank=True, choices=[(None, 'Выберите значение'), ('Одноместный', 'Одноместный'), ('Двухместный', 'Двухместный'), ('Трехместный', 'Трехместный'), ('Люкс', 'Люкс')], max_length=15, null=True, verbose_name='Тип номера'),
        ),
    ]
