# Generated by Django 4.2 on 2023-04-17 17:44

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='static/default.jpeg', upload_to=core.utils.user_directory_path, verbose_name='Фото профиля'),
        ),
    ]
